name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Generate .env file
        uses: horlakz/secretenv@v1
        with:
          secrets_json: ${{ toJSON(secrets) }}


      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -o thryvo

  run_app:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Reload systemd
        run: sudo systemctl daemon-reload

      - name: Restart service
        run: sudo systemctl restart api_thryvo_com_ng.service
